### ISSUE TITLE
Proposal: unpublish unmaintained extension

### ISSUE THREAD

**Issue by ssbarnea** [VSChina/vsc-extension-ansible#289]
I would like to propose unpublishing this extension from the marketplace as it keeps being found as 1st pick for any search on "ansible", even if it was marked as RETIRED more than 6 months ago and last active maintenance was done years ago.

Unpublishing the extension **would clearly serve vscode users** as in its current form is not usable with current versions of vscode and goes into conflict with other popular and maintained extensions.

As you know "unpublish" action is a reversible action which allows you to easily reinstate its listing if ever desired to resurrect the project.

**Comment by FlorianLaunay** [comment]
@yungezz could you please take a look?

**Comment by yungezz** [comment]
hi @florianlaunay, I'm not working on vscode ansible extension for years. add @mybayern1974 for this

**Comment by ssbarnea** [comment]
Or maybe @aeschli could help? I seen that the retirement was made by him.

**Comment by aeschli** [comment]
Did you try to do it on https://marketplace.visualstudio.com/manage ?

**Comment by njuCZ** [comment]
thanks for all of your suggestions. We have unpublished this extension.
